# Generated by Django 5.2.8 on 2025-11-13 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField()),
                ('dados_json', models.JSONField()),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
