# Generated by Django 5.2.8 on 2025-11-18 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='analise',
            old_name='data_execucao',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='status',
        ),
        migrations.AddField(
            model_name='analise',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='analise',
            name='cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='dados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analise',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analise',
            name='tipo',
            field=models.CharField(choices=[('sla_mensal', 'SLA Mensal'), ('cenarios', 'Análise de Cenários')], max_length=50),
        ),
    ]
