# Generated by Django 5.2.8 on 2025-11-19 19:11

import vamos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamos', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='protocolo',
            field=models.CharField(default=vamos.models.gerar_protocolo, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='data_resposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='protocolo',
            field=models.CharField(default=vamos.models.gerar_protocolo, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resposta_admin',
            field=models.TextField(blank=True, help_text='Resposta oficial do suporte', null=True),
        ),
    ]
