# Generated by Django 5.2.8 on 2025-12-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamos', '0004_analise_protocolo_ticket_data_resposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='termos_aceitos_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
