# Generated by Django 4.2.11 on 2026-05-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamos', '0006_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='termos_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='perfil',
            name='termos_versao',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
