# Generated by Django 6.0.1 on 2026-01-12 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_node_id', models.CharField(blank=True, help_text='ID do node atual', max_length=50, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em Progresso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(default=dict, help_text='Dados acumulados do procedimento')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_procedures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instância de Procedimento',
                'verbose_name_plural': 'Instâncias de Procedimentos',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='ID do node no template', max_length=50)),
                ('question', models.TextField(help_text='Pergunta/prompt apresentado')),
                ('answer', models.JSONField(help_text='Resposta do usuário (pode ser texto, número, etc.)')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_nodes', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='procedures.procedureinstance')),
            ],
            options={
                'verbose_name': 'Node Instance',
                'verbose_name_plural': 'Node Instances',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome do procedimento (ex: 'Sinistro')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição do procedimento')),
                ('version', models.CharField(default='1.0', help_text='Versão do template', max_length=20)),
                ('structure', models.JSONField(help_text='Estrutura JSON com os nodes do workflow')),
                ('is_active', models.BooleanField(default=True, help_text='Se o template está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Procedimento',
                'verbose_name_plural': 'Templates de Procedimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='procedureinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='procedures.proceduretemplate'),
        ),
    ]
