# Generated by Django 5.2.8 on 2025-12-04 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('chassi', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_ativo', models.CharField(blank=True, max_length=200, null=True)),
                ('n_contrato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Contrato')),
                ('segmento', models.CharField(blank=True, choices=[('AGRO', 'Agro'), ('PESADOS', 'Pesados'), ('INTRA', 'Intra'), ('OUTROS', 'Outros')], max_length=20, null=True)),
                ('tem_protecao_casco', models.BooleanField(default=False, verbose_name='Proteção do Casco?')),
                ('n_chamado', models.CharField(max_length=50, verbose_name='Nº Chamado (GEO/Vetor)')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da Ocorrência')),
                ('telefone_contato', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco_ativo', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.CharField(choices=[('FURTO_ROUBO', 'Furto / Roubo'), ('SINISTRO_PT', 'Sinistro / Perda Total'), ('INCENDIO_PT', 'Incêndio / Perda Total')], max_length=20)),
                ('check_bo', models.BooleanField(default=False, verbose_name='B.O. Oficial')),
                ('check_ficha', models.BooleanField(default=False, verbose_name='Ficha de Ocorrência')),
                ('check_cnh', models.BooleanField(default=False, verbose_name='CNH Condutor')),
                ('check_fotos', models.BooleanField(default=False, verbose_name='Fotos Avarias')),
                ('valor_fipe', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor FIPE')),
                ('modelo_implemento', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_implemento', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_seguradora', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_cliente', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tipo_processo', models.CharField(blank=True, choices=[('PAG_CLIENTE', 'Pagamento pelo Cliente (100%)'), ('PAG_SEGURADORA', 'Pagamento por Seguradora'), ('PAG_CLIENTE_20', 'Pagamento pelo Cliente (20% - Proteção)')], max_length=20, null=True)),
                ('setor_atual', models.CharField(choices=[('ABERTURA', 'Abertura / Triagem'), ('CLIENTE', 'Cliente'), ('MANUTENCAO', 'Manutenção'), ('DEPTO_SINISTRO', 'Depto. Sinistro'), ('FINANCEIRO', 'Financeiro'), ('GERENCIA', 'Gerência'), ('PRECIFICACAO', 'Precificação'), ('DESMOBILIZACAO', 'Desmobilização'), ('FINALIZADO', 'Finalizado')], default='ABERTURA', max_length=20)),
                ('responsavel_setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável Atual')),
                ('data_inicio_tratativa', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_interacao', models.DateTimeField(auto_now=True)),
                ('retornar_ate', models.DateField(blank=True, null=True, verbose_name='Prazo para Retorno')),
                ('data_envio_simpar', models.DateField(blank=True, null=True)),
                ('data_retorno_simpar', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_anterior', models.CharField(max_length=50)),
                ('setor_novo', models.CharField(max_length=50)),
                ('data_mudanca', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sinistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='sinistros.sinistro')),
            ],
        ),
    ]
