# Generated by Django 5.2.8 on 2025-12-09 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistro',
            name='check_laudo',
        ),
        migrations.RemoveField(
            model_name='sinistro',
            name='data_envio_simpar',
        ),
        migrations.RemoveField(
            model_name='sinistro',
            name='data_inicio_tratativa',
        ),
        migrations.RemoveField(
            model_name='sinistro',
            name='data_retorno_simpar',
        ),
        migrations.RemoveField(
            model_name='sinistro',
            name='modelo_implemento',
        ),
        migrations.RemoveField(
            model_name='sinistro',
            name='tipo_processo',
        ),
        migrations.AddField(
            model_name='sinistro',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicosinistro',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='chassi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='check_bo',
            field=models.BooleanField(default=False, verbose_name='B.O.'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='check_cnh',
            field=models.BooleanField(default=False, verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='check_fotos',
            field=models.BooleanField(default=False, verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='data_ocorrencia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='endereco_ativo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='modelo_ativo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='motivo',
            field=models.CharField(choices=[('COLISAO', 'Colisão'), ('FURTO_ROUBO', 'Furto/Roubo'), ('INCENDIO', 'Incêndio'), ('NATUREZA', 'Fenômenos da Natureza'), ('TERCEIROS', 'Danos a Terceiros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='n_chamado',
            field=models.CharField(max_length=50, verbose_name='Nº Chamado'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='n_contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='placa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='retornar_ate',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo SLA'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='segmento',
            field=models.CharField(choices=[('AGRO', 'Agro (Máquinas/Implementos)'), ('PESADOS', 'Pesados (Caminhões)'), ('INTRA', 'Intralogística (Empilhadeiras)')], default='PESADOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='setor_atual',
            field=models.CharField(choices=[('ABERTURA', 'Abertura'), ('MANUTENCAO', 'Manutenção (Orçamento)'), ('CLIENTE', 'Aprovação Cliente'), ('JURIDICO', 'Jurídico/Sinistro'), ('FINANCEIRO', 'Financeiro (Pagamento)'), ('FINALIZADO', 'Finalizado')], default='ABERTURA', max_length=20),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='tem_protecao_casco',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='valor_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='valor_fipe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='valor_franquia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='valor_implemento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='valor_seguradora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
