# Generated by Django 5.2.8 on 2025-12-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistro',
            name='check_laudo',
            field=models.BooleanField(default=False, verbose_name='Laudo Pericial (BVQI)'),
        ),
        migrations.AddField(
            model_name='sinistro',
            name='valor_franquia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Franquia'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='motivo',
            field=models.CharField(choices=[('FURTO_ROUBO', 'Furto / Roubo'), ('SINISTRO_PT', 'Sinistro / Perda Total'), ('INCENDIO_PT', 'Incêndio / Perda Total'), ('COLISAO', 'Colisão (Avarias)')], max_length=20, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='n_contrato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Contrato'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='placa',
            field=models.CharField(max_length=20, verbose_name='Placa / Série'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='responsavel_setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='retornar_ate',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo (Retornar Até)'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='segmento',
            field=models.CharField(choices=[('AGRO', 'Agro (Máquinas/Implementos)'), ('PESADOS', 'Pesados (Caminhões)'), ('INTRA', 'Intra (Empilhadeiras/Outros)')], default='OUTROS', max_length=20, verbose_name='Segmento'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='setor_atual',
            field=models.CharField(choices=[('ABERTURA', 'Abertura'), ('CLIENTE', 'Com o Cliente'), ('MANUTENCAO', 'Manutenção (Orçamento)'), ('JURIDICO_SINISTRO', 'Depto. Sinistro / Jurídico'), ('VISTORIA', 'Vistoria (BVQI)'), ('FINANCEIRO', 'Financeiro (Pagamento)'), ('DESMOBILIZACAO', 'Desmobilização'), ('FINALIZADO', 'Finalizado')], default='ABERTURA', max_length=20),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='tem_protecao_casco',
            field=models.BooleanField(default=False, verbose_name='Tem Proteção do Casco?'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='tipo_processo',
            field=models.CharField(blank=True, choices=[('CLIENTE_100', 'Pagamento Cliente (100%)'), ('SEGURADORA', 'Pagamento Seguradora'), ('CLIENTE_20', 'Pagamento Cliente (20% - Proteção)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Previsto'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Recebido'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='valor_cliente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Cliente'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='valor_fipe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor FIPE'),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='valor_implemento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='valor_seguradora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Seguradora'),
        ),
    ]
