# Generated by Django 5.2.8 on 2025-12-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0002_remove_sinistro_check_laudo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=20, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('chassi', models.CharField(blank=True, max_length=100, null=True)),
                ('contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_custo', models.CharField(blank=True, max_length=50, null=True)),
                ('segmento', models.CharField(blank=True, max_length=50, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
