# Generated by Django 5.2.8 on 2025-12-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0003_frota'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistro',
            name='aguarda_aprovacao_os',
            field=models.BooleanField(default=False, help_text='Se o processo está aguardando aprovação de O.S.'),
        ),
        migrations.AddField(
            model_name='sinistro',
            name='aprovador_os',
            field=models.CharField(blank=True, help_text='Nome do aprovador da O.S., se houver', max_length=255, null=True),
        ),
    ]
