# Generated by Django 5.2.8 on 2025-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0004_sinistro_aguarda_aprovacao_os_sinistro_aprovador_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistro',
            name='aprovador_os',
            field=models.CharField(blank=True, help_text='Nome do aprovador da O.S., se houver', max_length=255, null=True, verbose_name='Aprovador O.S.'),
        ),
    ]
