# Generated by Django 5.2.8 on 2025-12-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0005_alter_sinistro_aprovador_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistro',
            name='aprovador_os',
            field=models.CharField(blank=True, help_text='Nome do aprovador da O.S., se houver', max_length=255, null=True),
        ),
    ]
