# Generated by Django 6.0.1 on 2026-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0006_alter_sinistro_aprovador_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistro',
            name='setor_atual',
            field=models.CharField(choices=[('ABERTURA', 'Abertura'), ('MANUTENCAO', 'Manutenção (Orçamento)'), ('CLIENTE', 'Aprovação Cliente'), ('PRECIFICACAO', 'Precificação'), ('FINANCEIRO', 'Financeiro (Pagamento)'), ('DESMOBILIZACAO', 'Desmobilização / Medição'), ('DEPTO_SINISTRO', 'Depto. Sinistro'), ('FINALIZADO', 'Finalizado')], default='ABERTURA', max_length=20),
        ),
    ]
