# Generated by Django 6.0.1 on 2026-01-20 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0007_alter_setor_atual_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistro',
            name='setor_atual',
            field=models.CharField(choices=[('ABERTURA', 'Abertura'), ('CLIENTE', 'Aprovação Cliente'), ('PRECIFICACAO', 'Precificação'), ('FINANCEIRO', 'Financeiro (Pagamento)'), ('DESMOBILIZACAO_MEDICAO', 'Desmobilização / Medição'), ('DEPTO_SINISTRO', 'Depto. Sinistro'), ('MANUTENCAO', 'Manutenção (Aprovação de O.S)'), ('MANUTENCAO_CRIACAO', 'Manutenção (Criação de Processo)'), ('FINALIZADO', 'Finalizado')], default='ABERTURA', max_length=30),
        ),
        migrations.CreateModel(
            name='CustomSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Chave única do setor (ex: CUSTOM_SETOR_1)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Nome exibido do setor', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Se o setor está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setor Customizado',
                'verbose_name_plural': 'Setores Customizados',
                'ordering': ['display_name'],
            },
        ),
    ]
