# Generated by Django 6.0.1 on 2026-01-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0008_alter_sinistro_setor_atual_customsetor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetor',
            name='sla_days',
            field=models.IntegerField(blank=True, default=None, help_text='Prazo SLA em dias corridos (deixe vazio para SEM PRAZO)', null=True),
        ),
    ]
