# Generated by Django 4.2.11 on 2026-08-07 16:17

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0009_customsetor_sla_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frota',
            name='chassi',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='frota',
            name='cliente',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True)),
        ),
        migrations.AlterField(
            model_name='frota',
            name='contrato',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='frota',
            name='placa',
            field=django_cryptography.fields.encrypt(models.CharField(db_index=True, max_length=20, unique=True)),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='chassi',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='cliente',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='n_contrato',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='placa',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20)),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='telefone_contato',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True)),
        ),
    ]
